# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  host: localhost
  database: raceresults_development
  username: raceresults_user
  password: raceresults_password
  
test:
  <<: *default
  host: localhost
  database: raceresults_test
  username: raceresults_user
  password: raceresults_password

production:
  <<: *default
  host: localhost
  database: raceresults_production
