# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a5c4265c6b0b46bf2984540020694dc70fcf91a7b25db885816dfe4a5d6c5e93e6b59bd87e493ab2112a567410c80a3604b41b2eefa65416c158ad071e2c94b

test:
  secret_key_base: b15cedcbc609a7456f7d93a1105242ae9a4bb713504dc0483f1eddcc5fa7bc0ce0447564a698e37d2871f8a1c9299a98ab7987788b9cec97d10fd80bda695d7d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
